name: Run Playwright tests

on: 
  push:
    branches:
      - feature/*
    paths:
      - 'cms/**'

jobs:
  # this is needed to wait for the new docker image to be build and published to the registry
  # so that we can use the image to run ui of the needed commit related version as part of home-local-env
  # the idea is taken from here https://stackoverflow.com/a/71489231
  push_to_registry:
    uses: ./.github/workflows/cms-docker-build-and-push.yml
    # without this it cannot login to the registry
    secrets: inherit

  run-playwright-tests:
    runs-on: ubuntu-24.04
    needs: push_to_registry

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.18.0]

    steps:
      - name: Checkout home-local-env
        uses: actions/checkout@v4
        with:
          repository: TourmalineCore/home-local-env
          ref: feature/cms_from_monorepo

      - name: Deploy Local Env to Kind k8s
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # we need to override "latest" image tag of service inside home-local-env to run tests against the current commit service version and not against latest from master
            # We tried to use yq to change the image tag, but in the values files for helmfile we have non-yaml code that yq can`t parse or ignore
            # so for that reason we use Stream EDitor which can find needed string using regular expressions and change it to a new value
            # The -i flag is needed to write new image tag directly to values file
            sed -i "0,/tag:.*/s//tag: \"sha-${{ github.sha }}\"/" deploy/values-cms.yaml.gotmpl

            # we need to override "latest" ref of service chart inside home-local-env to run tests against the current commit service chart version and not against latest from master
            sed -i "0,/cms?ref=.*/s//cms?ref=${{ github.sha }}/" deploy/helmfile.yaml
            
            sed -i "0,/cms\/ci\/values.yaml?ref=.*/s//cms\/ci\/values.yaml?ref=${{ github.sha }}/" deploy/helmfile.yaml

            kind create cluster --name home --config kind-local-config.yaml --kubeconfig ./.home-cluster-kubeconfig
            
            export KUBECONFIG=$(pwd)/.home-cluster-kubeconfig

            helmfile --environment local --namespace local -f deploy/helmfile.yaml apply
          push: never

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # sparse-checkout is needed to clone cms folder only. 
          # Cone mode is disabled to not clone other files in top-level folder
          sparse-checkout: 'cms'
          sparse-checkout-cone-mode: false

        # This step is needed because all steps runs from root folder and there is several options how to solve this problem
        # Option #1: change working-directory of each step
        # Option #2: move subfolder to root folder
        # Option #2 was chosen because it allows the folder to be moved in a single action
      - name: Move subfolder to current(top-level) folder
        run: |
          mv cms/* .
          rm -rf cms

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  
      # let's cache the binaries of installed browsers that we don't re-install them every time from scratch
      - name: Cache playwright browsers
        id: cache-playwrightbrowsers
        uses: actions/cache@v4
        env:
          cache-name: cache-playwright-browsers
        with:
          # caching browsers binaries
          # this path is taken from here https://playwright.dev/docs/browsers#managing-browser-binaries
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browsers
        if: steps.cache-playwrightbrowsers.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps

      - name: Playwright run
        run: npx playwright test --reporter=list,html
        env:
          SERVER_URL: 'http://localhost:40120/cms'
    
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 7
