name: Run playwright E2E tests

# ToDo should it be triggered only as part of an open PR?
# currently it triggers for any commit in a FB
on: 
  push:
    branches:
      - feature/*
    paths:
      - 'ui/**'
  # to allow to wait for a e2e tests to be passed to proceed in another workflow
  workflow_call:
  
jobs:
  # this is needed to wait for the new docker image to be build and published to the registry
  # so that we can use the image to run ui of the needed commit related version as part of home-local-env
  # the idea is taken from here https://stackoverflow.com/a/71489231
  push_to_registry:
    uses: ./.github/workflows/ui-local-env-docker-build-and-push.yml
    # without this it cannot login to the registry
    secrets: inherit

  run-playwright-e2e-tests:
    runs-on: ubuntu-24.04
    needs: push_to_registry

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.18.0]

    steps:
      - name: Checkout home-local-env
        uses: actions/checkout@v4
        with:
          repository: TourmalineCore/home-local-env

      - name: Deploy Local Env to Kind k8s
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # we need to override "latest" image tag of ui inside local-env to run e2e against the current commit ui version and not against latest from master
            # We tried to use yq to change the image tag, but in the values files for helmfile we have non-yaml code that yq can`t parse or ignore
            # so for that reason we use Stream EDitor which can find needed string using regular expressions and change it to a new value
            # The -i flag is needed to write new image tag directly to values file
            sed -i "0,/tag:.*/s//tag: \"local-env-sha-${{ github.sha }}\"/" deploy/values-ui.yaml.gotmpl

             # we need to override "latest" ref of service chart inside local-env to run tests against the current commit service chart version and not against latest from master
            sed -i "0,/git+https:\/\/github.com\/TourmalineCore\/${{ github.event.repository.name }}.git?ref=.*/s//git+https:\/\/github.com\/TourmalineCore\/${{ github.event.repository.name }}.git?ref=${{ github.sha }}/" deploy/helmfile.yaml
            
            sed -i "0,/git::https:\/\/github.com\/TourmalineCore\/${{ github.event.repository.name }}.git@\/ui\/ci\/values.yaml?ref=.*/s//git::https:\/\/github.com\/TourmalineCore\/${{ github.event.repository.name }}.git@\/ui\/ci\/values.yaml?ref=${{ github.sha }}/" deploy/helmfile.yaml

            kind create cluster --name home --config kind-local-config.yaml --kubeconfig ./.home-cluster-kubeconfig
            
            export KUBECONFIG=$(pwd)/.home-cluster-kubeconfig

            helmfile --environment local --namespace local -f deploy/helmfile.yaml apply
          push: never

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # sparse-checkuout is needed to clone cms folder only. 
          # Cone mode is disabled to not clone other files in root folder
          sparse-checkout: 'ui'
          sparse-checkout-cone-mode: false
      
      - name: Move subfolder to root
        run: |
          mv ui/* .
          rm -rf ui

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  
      # let's cache the binaries of installed browsers that we don't re-install them every time from scratch
      - name: Cache playwright browsers
        id: cache-playwrightbrowsers
        uses: actions/cache@v4
        env:
          cache-name: cache-playwright-browsers
        with:
          # caching browsers binaries
          # this path is taken from here https://playwright.dev/docs/browsers#managing-browser-binaries
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browsers
        if: steps.cache-playwrightbrowsers.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps

      - name: Playwright run
        run: npx playwright test --config=playwright.e2e.config.ts --reporter=list,html
    
        env:
          FRONTEND_URL: http://localhost:40120 
          CMS_URL: http://localhost:40120/cms
          CMS_EMAIL: admin@init-strapi-admin.strapi.io
          CMS_PASSWORD: admin

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 7